theme: jekyll-theme-midnight
title: EdgeTX
description: The cutting edge open-source firmware for your R/C radio
repository: EdgeTX/edgetx.github.io
github:
  repository_url: https://github.com/EdgeTX
