# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem "github-pages", "~> 215", group: :jekyll_plugins
gem "jekyll-theme-slate", "~> 0.1.1"

